# Generated by Django 5.2.7 on 2025-10-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdBatches',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bird_type', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('expense_type', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.birdbatches')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('income_type', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.birdbatches')),
            ],
        ),
        migrations.CreateModel(
            name='Losses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cause', models.TextField(max_length=200)),
                ('notes', models.TextField(verbose_name=200)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.birdbatches')),
            ],
        ),
    ]
