# Generated by Django 5.2.7 on 2025-10-28 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdbatches',
            name='cost_per_bird',
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birdbatches',
            name='date_in',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birdbatches',
            name='notes',
            field=models.CharField(default='This is a note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birdbatches',
            name='quantity',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='amount',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='losses',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='losses',
            name='quantity',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='losses',
            name='value_loss',
            field=models.IntegerField(default=3000000),
            preserve_default=False,
        ),
    ]
