# Generated by Django 5.2.7 on 2025-11-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0003_alter_birdbatches_id_alter_expenses_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BirdBatches',
            new_name='BirdBatch',
        ),
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='Losses',
            new_name='Loss',
        ),
    ]
