# Generated by Django 5.2.7 on 2025-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0004_rename_birdbatches_birdbatch_rename_expenses_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdbatch',
            name='notes',
            field=models.TextField(),
        ),
    ]
