# Generated by Django 5.2.7 on 2025-12-13 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0005_alter_birdbatch_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='cost_per_unit',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expense_type',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='amount',
            new_name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='birdbatch',
            name='batch_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='item',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
