# Generated by Django 5.2.7 on 2025-12-14 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0006_rename_amount_expense_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost_per_unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('item', models.TextField(max_length=200)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultry.birdbatch')),
            ],
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
