# Generated by Django 5.2.7 on 2026-01-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poultry', '0007_sale_delete_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceSummary',
        ),
    ]
